version: "3.7"

services:
  db:
    image: opavlova/db-mysql:5.7-test
    container_name: db
    hostname: db
    ports:
      - "13306:3306"
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-P", "3306", "-u", "root", "--password=root", "-e", "select 1", "DOCKERDB"]
      interval: 1s
      timeout: 3s
      retries: 30

  spring:
    build: .
    container_name: spring-demo
    hostname: spring-demo
    ports:
      - "18000:8000"
    depends_on:
      - db
    restart: on-failure

